# Generated by Django 5.1.3 on 2024-11-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_servico_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar valvula do motor'), ('TO', 'Troca de Oleo'), ('B', 'Banlanceamento')], max_length=3),
        ),
        migrations.AlterField(
            model_name='servico',
            name='protocolo',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
