# Generated by Django 5.1.3 on 2024-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_categoriamanutencao_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamanutencao',
            name='titulo',
            field=models.CharField(choices=[('TVM', 'Trocar valvula do motor'), ('TO', 'Troca de Oleo'), ('B', 'Banlanceamento'), ('LS', 'Lavagem Simples'), ('LC', 'Lavagem Completa')], max_length=3),
        ),
    ]
