# Generated by Django 5.1.3 on 2024-11-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_servico_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
    ]
