# Generated by Django 5.1.3 on 2024-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_alter_servico_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
    ]
